// <auto-generated />
using System;
using CITNASDaily.Repositories.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CITNASDaily.Repositories.Migrations
{
    [DbContext(typeof(NASContext))]
    [Migration("20231002075614_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CITNASDaily.Entities.Models.ActivitiesSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivitiesOfTheDay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkillsLearned")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValuesLearned")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ActivitiesSummary");
                });

            modelBuilder.Entity("CITNASDaily.Entities.Models.NAS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Course")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateStarted")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.Property<int?>("SuperiorEvaluationRatingId")
                        .HasColumnType("int");

                    b.Property<int>("SuperiorValidationId")
                        .HasColumnType("int");

                    b.Property<int>("UnitsAllowed")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("YearLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId");

                    b.HasIndex("SuperiorEvaluationRatingId");

                    b.HasIndex("UserId");

                    b.ToTable("NAS");
                });

            modelBuilder.Entity("CITNASDaily.Entities.Models.OAS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("OAS");
                });

            modelBuilder.Entity("CITNASDaily.Entities.Models.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SuperiorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SuperiorId")
                        .IsUnique();

                    b.ToTable("Office");
                });

            modelBuilder.Entity("CITNASDaily.Entities.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "OAS"
                        });
                });

            modelBuilder.Entity("CITNASDaily.Entities.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BrokenSched")
                        .HasColumnType("bit");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("NASId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<float>("TotalHours")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("NASId");

                    b.ToTable("Schedule");
                });

            modelBuilder.Entity("CITNASDaily.Entities.Models.SummaryEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcademicPerformance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnrollmentAllowed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("SuperiorOverallRating")
                        .HasColumnType("real");

                    b.Property<string>("TimekeepingStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnitsAllowed")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SummaryEvaluation");
                });

            modelBuilder.Entity("CITNASDaily.Entities.Models.Superior", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Superior");
                });

            modelBuilder.Entity("CITNASDaily.Entities.Models.SuperiorEvaluationRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("AttendanceAndPunctuality")
                        .HasColumnType("real");

                    b.Property<float>("AttitudeAndWorkBehaviour")
                        .HasColumnType("real");

                    b.Property<float>("OverallAssessment")
                        .HasColumnType("real");

                    b.Property<float>("OverallRating")
                        .HasColumnType("real");

                    b.Property<float>("QualOfWorkInput")
                        .HasColumnType("real");

                    b.Property<float>("QualOfWorkOutput")
                        .HasColumnType("real");

                    b.Property<int>("SuperiorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SuperiorId");

                    b.ToTable("SuperiorEvaluationRating");
                });

            modelBuilder.Entity("CITNASDaily.Entities.Models.TimekeepingSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NASId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NASId");

                    b.ToTable("TimekeepingSummary");
                });

            modelBuilder.Entity("CITNASDaily.Entities.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CITNASDaily.Entities.Models.NAS", b =>
                {
                    b.HasOne("CITNASDaily.Entities.Models.Office", "Office")
                        .WithMany("Nas")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CITNASDaily.Entities.Models.SuperiorEvaluationRating", "SuperiorEvaluationRating")
                        .WithMany()
                        .HasForeignKey("SuperiorEvaluationRatingId");

                    b.HasOne("CITNASDaily.Entities.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Office");

                    b.Navigation("SuperiorEvaluationRating");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CITNASDaily.Entities.Models.OAS", b =>
                {
                    b.HasOne("CITNASDaily.Entities.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CITNASDaily.Entities.Models.Office", b =>
                {
                    b.HasOne("CITNASDaily.Entities.Models.Superior", "Superior")
                        .WithOne("Office")
                        .HasForeignKey("CITNASDaily.Entities.Models.Office", "SuperiorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Superior");
                });

            modelBuilder.Entity("CITNASDaily.Entities.Models.Schedule", b =>
                {
                    b.HasOne("CITNASDaily.Entities.Models.NAS", "NAS")
                        .WithMany()
                        .HasForeignKey("NASId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NAS");
                });

            modelBuilder.Entity("CITNASDaily.Entities.Models.Superior", b =>
                {
                    b.HasOne("CITNASDaily.Entities.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CITNASDaily.Entities.Models.SuperiorEvaluationRating", b =>
                {
                    b.HasOne("CITNASDaily.Entities.Models.Superior", "Superior")
                        .WithMany()
                        .HasForeignKey("SuperiorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Superior");
                });

            modelBuilder.Entity("CITNASDaily.Entities.Models.TimekeepingSummary", b =>
                {
                    b.HasOne("CITNASDaily.Entities.Models.NAS", "NAS")
                        .WithMany()
                        .HasForeignKey("NASId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NAS");
                });

            modelBuilder.Entity("CITNASDaily.Entities.Models.User", b =>
                {
                    b.HasOne("CITNASDaily.Entities.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CITNASDaily.Entities.Models.Office", b =>
                {
                    b.Navigation("Nas");
                });

            modelBuilder.Entity("CITNASDaily.Entities.Models.Superior", b =>
                {
                    b.Navigation("Office");
                });
#pragma warning restore 612, 618
        }
    }
}
