// <auto-generated />
using System;
using CITNASDaily.Repositories.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CITNASDaily.Repositories.Migrations
{
    [DbContext(typeof(NASContext))]
    partial class NASContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CITNASDaily.Entities.Models.NAS", b =>
                {
                    b.Property<int>("NASId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NASId"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Course")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateStarted")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.Property<int?>("SuperiorEvaluationRatingSuperiorEvaluationId")
                        .HasColumnType("int");

                    b.Property<int>("SuperiorValidationId")
                        .HasColumnType("int");

                    b.Property<int>("UnitsAllowed")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("YearLevel")
                        .HasColumnType("int");

                    b.HasKey("NASId");

                    b.HasIndex("OfficeId");

                    b.HasIndex("SuperiorEvaluationRatingSuperiorEvaluationId");

                    b.HasIndex("UserId");

                    b.ToTable("NAS");
                });

            modelBuilder.Entity("CITNASDaily.Entities.Models.Office", b =>
                {
                    b.Property<int>("OfficeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfficeId"));

                    b.Property<int>("SuperiorId")
                        .HasColumnType("int");

                    b.HasKey("OfficeId");

                    b.HasIndex("SuperiorId")
                        .IsUnique();

                    b.ToTable("Office");
                });

            modelBuilder.Entity("CITNASDaily.Entities.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "OAS"
                        });
                });

            modelBuilder.Entity("CITNASDaily.Entities.Models.Superior", b =>
                {
                    b.Property<int>("SuperiorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuperiorId"));

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SuperiorId");

                    b.HasIndex("UserId");

                    b.ToTable("Superior");
                });

            modelBuilder.Entity("CITNASDaily.Entities.Models.SuperiorEvaluationRating", b =>
                {
                    b.Property<int>("SuperiorEvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuperiorEvaluationId"));

                    b.Property<float>("AttendanceAndPunctuality")
                        .HasColumnType("real");

                    b.Property<float>("AttitudeAndWorkBehaviour")
                        .HasColumnType("real");

                    b.Property<float>("OverallAssessment")
                        .HasColumnType("real");

                    b.Property<float>("OverallRating")
                        .HasColumnType("real");

                    b.Property<float>("QualOfWorkInput")
                        .HasColumnType("real");

                    b.Property<float>("QualOfWorkOutput")
                        .HasColumnType("real");

                    b.Property<int>("SuperiorId")
                        .HasColumnType("int");

                    b.HasKey("SuperiorEvaluationId");

                    b.HasIndex("SuperiorId");

                    b.ToTable("SuperiorEvaluationRating");
                });

            modelBuilder.Entity("CITNASDaily.Entities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CITNASDaily.Entities.Models.NAS", b =>
                {
                    b.HasOne("CITNASDaily.Entities.Models.Office", "Office")
                        .WithMany("Nas")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CITNASDaily.Entities.Models.SuperiorEvaluationRating", "SuperiorEvaluationRating")
                        .WithMany()
                        .HasForeignKey("SuperiorEvaluationRatingSuperiorEvaluationId");

                    b.HasOne("CITNASDaily.Entities.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");

                    b.Navigation("SuperiorEvaluationRating");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CITNASDaily.Entities.Models.Office", b =>
                {
                    b.HasOne("CITNASDaily.Entities.Models.Superior", "Superior")
                        .WithOne("Office")
                        .HasForeignKey("CITNASDaily.Entities.Models.Office", "SuperiorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Superior");
                });

            modelBuilder.Entity("CITNASDaily.Entities.Models.Superior", b =>
                {
                    b.HasOne("CITNASDaily.Entities.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CITNASDaily.Entities.Models.SuperiorEvaluationRating", b =>
                {
                    b.HasOne("CITNASDaily.Entities.Models.Superior", "Superior")
                        .WithMany()
                        .HasForeignKey("SuperiorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Superior");
                });

            modelBuilder.Entity("CITNASDaily.Entities.Models.Office", b =>
                {
                    b.Navigation("Nas");
                });

            modelBuilder.Entity("CITNASDaily.Entities.Models.Superior", b =>
                {
                    b.Navigation("Office");
                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Superior");
                });
#pragma warning restore 612, 618
        }
    }
}
